[project]
name = "test-pydantic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "devtools>=0.12.2",
    "dotenv>=0.9.9",
    "pydantic-ai>=0.1.6",
]
